version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  node-executor:
    docker:
      - image: circleci/node:14.15.5-browsers
  docker-python:
    docker:
      - image: circleci/python:3.7

references:
  workspace_root: &workspace_root '~'
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - *attach_workspace
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Set GitHub username and email
          command: git config user.email "ci@hackney.gov.uk" && git config user.name "lbhackney-automation"
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - /home/circleci/.cache/Cypress
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  unit-tests:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run typecheck
          command: yarn type-check
      - run:
          name: Run tests
          command: yarn test -w 2

  build:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - project/build

  e2e:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: Run E2E
          command: yarn e2e
      - store_artifacts:
          path: ~/project/cypress/screenshots
      - store_artifacts:
          path: ~/project/cypress/videos

  owasp-zap-baseline-scan:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - *attach_workspace

      - run:
          name: Build application
          command: |
            yarn build

      - run:
          name: Run application in background
          command: |
            PORT=3000 yarn start
          background: true

      - run:
          name: Pull owasp zap docker image
          command: docker pull owasp/zap2docker-stable

      - run:
          name: ZAP baseline test of application
          # Only fail on error code 1, which indicates at least one FAIL was found.
          # error codes 2 & 3 indicate WARN or other, and should not break the run
          command: |
              (
                docker run -t owasp/zap2docker-stable zap-baseline.py \
                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/zap-baseline.conf \
                -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):3000 || \
                if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
              )

  build-deploy-staging:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - run:
          name: deploy
          command: yarn --production=true && sudo npm i -g serverless && sls deploy --stage staging

  build-deploy-production:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - run:
          name: deploy
          command: yarn --production=true && sudo npm i -g serverless && sls deploy -s production

  generate-draft-github-release:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - run:
          name: delete stale draft GitHub releases
          command: yarn delete-draft-github-releases
      - run:
          name: generate draft GitHub release
          command: yarn release --github.draft --no-git.push --no-git.tag

  generate-github-release:
    executor: aws-cli/default
    steps:
      - *attach_workspace
      - add_ssh_keys:
          fingerprints:
            - 'd0:bd:5a:9f:c3:17:88:3a:df:03:42:7b:f6:f7:3c:72'
      - run:
          name: delete stale draft GitHub releases
          command: yarn delete-draft-github-releases
      - run:
          name: generate release
          command: yarn release

  assume-role-staging:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_STAGING
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  assume-role-production:
    executor: docker-python
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: $AWS_ACCOUNT_PRODUCTION
          profile_name: default
          role: 'LBH_Circle_CI_Deployment_Role'
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - build:
          requires:
            - unit-tests
      - e2e:
          requires:
            - install-dependencies
      - owasp-zap-baseline-scan:
          requires:
            - install-dependencies
      - generate-draft-github-release:
          requires:
            - unit-tests
            - e2e
            - build
          filters:
            branches:
              only: main
      - assume-role-staging:
          context: api-assume-role-staging-context
          requires:
            - unit-tests
            - e2e
            - build
          filters:
            branches:
              only: main
      - build-deploy-staging:
          requires:
            - assume-role-staging
          filters:
            branches:
              only: main
      - permit-deploy-production:
          type: approval
          requires:
            - build-deploy-staging
          filters:
            branches:
              only: main
      - assume-role-production:
          context: api-assume-role-production-context
          requires:
            - permit-deploy-production
          filters:
            branches:
              only: main
      - build-deploy-production:
          requires:
            - assume-role-production
          filters:
            branches:
              only: main
      - generate-github-release:
          requires:
            - build-deploy-production
          filters:
            branches:
              only: main
